# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meepo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='born_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pet',
            name='death_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
